[versions]
octokod = "0.1.0"

agp = "9.3.0"
kotlin = "2.4.10"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.37.0"
dokka = "2.2.0"
bcv = "0.18.1"
korro = "0.2.2"

ktor = "3.4.2"
kotlinx-datetime = "0.7.1"

[libraries]
# build plugins
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
android-kotlin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
vanniktech-maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktechMavenPublish" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
korro = { id = "io.github.devcrocod.korro", version.ref = "korro" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
